--CRIA UM LOGIN
CREATE LOGIN mayara WITH PASSWORD = '134';

--CRIAR UM USUARIO DENTRO DO BANCO DE DADOS
CREATE USER mayara FOR LOGIN mayara;

--COMANDO DENY - BLOQUEIA O ACESSO
DENY INSERT, UPDATE, DELETE
TO mayara;

--COMANDO REVOKE - REVERTE 
REVOKE INSERT, UPDATE, DELETE
TO mayara;